name: turtleott
description: TurtleOTT IPTV/OTT player.
version: 1.2.2+21

publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  wakelock_plus: ^1.4.0
  web_socket_channel: ^3.0.3
  equatable: ^2.0.7
  google_fonts: ^6.3.0
  shared_preferences: ^2.5.3
  video_player_web_hls: ^1.3.0
  get_it: ^8.2.0
  numberpicker: ^2.1.2
  url_launcher: ^6.3.2
  flutter_bloc: ^9.1.1

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dart_chromecast:
    git:
      url: https://github.com/fastogt/dart_chromecast.git
      ref: master
  fastotv_device_info:
    git:
      url: https://gitlab.com/fastogt/fastotv_device_info.git
      ref: master
  flutter_fastotv_common:
    git:
      url: https://gitlab.com/fastogt/flutter_fastotv_common.git
      ref: master
  crocott_dart:
    git:
      url: https://gitlab.com/fastogt/fastocloud_ott/crocott_dart.git
      ref: main
  player:
    git:
      url: https://gitlab.com/fastogt/flutter_fastotv_player.git
      ref: standard

dev_dependencies:
  dart_rules:
    git:
      url: https://github.com/fastogt/dart_rules.git
      ref: main
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - install/assets/
    - install/assets/categories/
    - install/lang/
